### PR TITLE
Fix registration of the proxy autoloader

### LINKED ISSUE #519: Proxy autoloader is not registered
See https://github.com/doctrine/mongodb-odm/issues/1920 for original discussion. The bundle should automatically register the autoloader for proxies to ensure proxies are not needlessly regenerated.

### PR DESCRIPTION
**Pull request by alcaeus**
Fixes #519 and https://github.com/doctrine/mongodb-odm/issues/1920.

@Rybbow could you give this a spin and let me know if this fixes your issue?

### CODE REVIEW

File: DoctrineMongoDBBundle.php [hunk 1]
```diff
@@ -54,56 +49,21 @@ public function getContainerExtension()
...
-
-                    foreach ($classes as $classMetadata) {
-                        if ($classMetadata->name !== $originalClassName) {
-                            continue;
-                        }
-
-                        $dm->getProxyFactory()->generateProxyClasses([$classMetadata]);
-                    }
-                }
+        $this->registerAutoloader($registry->getManager());
```
Comment (malarzm) [inline DoctrineMongoDBBundle.php]: What if there's more than one manager?

Comment (alcaeus) [reply DoctrineMongoDBBundle.php]: I was thinking the same, but the proxy namespace is shared among document managers, so I would think the autoloader would be the same for all managers. I can take a look to see whether there would be any differences.

Comment (malarzm) [reply DoctrineMongoDBBundle.php]: Ah indeed, I thought that each manager can have its own namespace defined 👍

Comment (alcaeus) [reply DoctrineMongoDBBundle.php]: Took another look: since we use the same values of `proxy_dir` and `auto_generate_proxy_classes` for all document managers, checking only the default manager will work as expected for the current configuration. If people decide to override the configuration for a single document manager, they'll have to ensure autoloading for said manager still works as expected.
