### PR TITLE
fix: UniqueEntity::$service is considered final

### LINKED ISSUE #741: UniqueEntity::$service is considered final
Running a test suite in a Symfony 6.1 application throws a deprecation notice:
```
The "Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity::$service" property is considered final. You should not override it in "Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique".
```

This is because `Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique` class overrides `$service` property with a different default value.

Another way to override it would be to copy the constructor parameters and set the default value there.

https://github.com/doctrine/DoctrineMongoDBBundle/blob/4.6.x/Validator/Constraints/Unique.php

### PR DESCRIPTION
**Pull request by divine**
Fix #741.

### CODE REVIEW

**Comment by franmomu** [comment]
Thanks @divine! what about using the suggested approach by [symfony](https://github.com/symfony/symfony/blob/73e65dc8e745b4f696db4a9631c4d866ab248a8e/UPGRADE-6.1.md#all-components): 

> Public and protected properties are now considered final; instead of overriding a property, consider setting its value in the constructor

That way a user can use `Unique` with their own service without overriding the class (I guess it unlikely to happen, but it could happen)

**Comment by divine** [comment]
Does it look better now?

Thanks!

File: Validator/Constraints/Unique.php [hunk 1]
```diff
@@ -16,6 +16,35 @@
...
+        string $errorPath = null,
+        bool|string|array $ignoreNull = null,
+        array $groups = null,
+        $payload = null,
+        array $options = []
+    ) {
+        parent::__construct(
+            $fields,
+            $message,
+            'doctrine_odm.mongodb.unique',
```
Comment (franmomu) [inline Validator/Constraints/Unique.php]:
```suggestion
        string $service = 'doctrine_odm.mongodb.unique',
        string $em = null,
        string $entityClass = null,
        string $repositoryMethod = null,
        string $errorPath = null,
        bool|string|array $ignoreNull = null,
        array $groups = null,
        $payload = null,
        array $options = []
    ) {
        parent::__construct(
            $fields,
            $message,
            $service,
```

This way the user can specify the service, otherwise the one from the constructor is not used

File: Validator/Constraints/Unique.php [hunk 2]
```diff
@@ -16,6 +16,35 @@
...
+     */
+    public function __construct(
+        $fields,
+        string $message = null,
+        string $service = 'doctrine_odm.mongodb.unique',
+        string $em = null,
+        string $entityClass = null,
+        string $repositoryMethod = null,
+        string $errorPath = null,
+        bool|string|array $ignoreNull = null,
```
Comment (franmomu) [inline Validator/Constraints/Unique.php]:
```suggestion
     */
    public function __construct(
        $fields,
        string $message = null,
        string $service = 'doctrine_odm.mongodb.unique',
        string $em = null,
        string $entityClass = null,
        string $repositoryMethod = null,
        string $errorPath = null,
        bool $ignoreNull = null,
```
Now I see this, union types are introduced in PHP >= 8.0, so I guess we should stick to Symfony 5.4 constructor: https://github.com/symfony/symfony/blob/8492f10d29e929a83ccf6c306d40dbad69c9c80b/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php#L55

~Adding a "simple" test would be awesome, we would have realized of this.~ (Test added)

**Review by GromNaN — APPROVED** [review]

**Review by malarzm — APPROVED** [review]

**Comment by malarzm** [comment]
Thanks @divine and @franmomu!

**Comment by divine** [comment]
Hello,

Any ETA for a new release with this fix?

Thanks!

**Comment by malarzm** [comment]
Here you go :) https://github.com/doctrine/DoctrineMongoDBBundle/releases/tag/4.6.1
