### PR TITLE
Fix deprecations in CommandDataCollector

### LINKED ISSUE #855: Functions fromPHP() and toCanonicalExtendedJSON() is deprecated
### DoctrineMongoDBBundle version(s) affected

**4.7.0**, up to 5.1.x

### Description

On PHP version **8.3.12**, `ext-mongodb` version **1.20.0** and `DoctrineMongoDBBundle` version **4.7.0**  I got two deprecation messages:

`Deprecated:  Function MongoDB\BSON\fromPHP() is deprecated in vendor/doctrine/mongodb-odm-bundle/DataCollector/CommandDataCollector.php on line 39.` 

`Deprecated:  Function MongoDB\BSON\toCanonicalExtendedJSON() is deprecated in vendor/doctrine/mongodb-odm-bundle/DataCollector/CommandDataCollector.php on line 39.`

I can't upgrade PHP version on my project from 8.2.24 to 8.3.12 with these two deprecation messages.  
Please, check and fix! I will create a pull request soon.

### Possible Solution

1) Change method `collect()` of class `\Doctrine\Bundle\MongoDBBundle\DataCollector\CommandDataCollector`

from:

```php
34                static function (Command $command): array {
35                    $dbProperty = '$db';
36
37                    return [
38                        'database' => $command->getCommand()->$dbProperty ?? '',
39                        'command' => json_decode(toCanonicalExtendedJSON(fromPHP($command->getCommand()))),
40                        'durationMicros' => $command->getDurationMicros(),
41                    ];
42               },
```

to:

```php
34                static function (Command $command): array {
35                    $dbProperty = '$db';
36                    $document = Document::fromPHP($command->getCommand());
37
38                    return [
39                        'database' => $command->getCommand()->$dbProperty ?? '',
40                        'command' => json_decode($document->toCanonicalExtendedJSON()),
41                        'durationMicros' => $command->getDurationMicros(),
42                    ];
43                },
```

2) Update version of `ext-mongodb` in `composer.json` to [^1.16](https://github.com/mongodb/mongo-php-driver/blob/v1.16/src/BSON/Document.stub.php):

```
"ext-mongodb": "^1.16"
```

### PR DESCRIPTION
**Pull request by andrey-tech**
### Description

Fix deprecations in method `collect()` of class `\Doctrine\Bundle\MongoDBBundle\DataCollector\CommandDataCollector`.

| Q             | A
| ------------- | ---
| Branch?       | 4.7.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix issue #855
| License       | MIT
| Doc PR        |  -

Fix deprecations on PHP version **8.3** and `ext-mongodb` version **1.20**:

`Deprecated:  Function MongoDB\BSON\fromPHP() is deprecated in vendor/doctrine/mongodb-odm-bundle/DataCollector/CommandDataCollector.php on line 39.`

`Deprecated:  Function MongoDB\BSON\toCanonicalExtendedJSON() is deprecated in vendor/doctrine/mongodb-odm-bundle/DataCollector/CommandDataCollector.php on line 39.`

### CODE REVIEW

File: DataCollector/CommandDataCollector.php [hunk 1]
```diff
@@ -33,10 +32,11 @@ public function collect(Request $request, Response $response, ?Throwable $except
             'commands' => array_map(
                 static function (Command $command): array {
                     $dbProperty = '$db';
+                    $document   = Document::fromPHP($command->getCommand());
```
Comment (alcaeus) [inline DataCollector/CommandDataCollector.php]: @jmikola This reminds me that we should have a way to get the command document as BSON so we can safe ourselves the round trip conversion.

**Review by alcaeus — APPROVED** [review]
LGTM. I'll have to take a look at what phpcs is complaining about.

**Comment by alcaeus** [comment]
Rebased onto 5.0.x as we no longer support 4.x.

**Comment by andrey-tech** [comment]
[alcaeus](https://github.com/alcaeus)
> Rebased onto 5.0.x as we no longer support 4.x.

Could you please copy changes from this my PR to branch 4.7.x? I can't migrate away from annotations (4.7.x) to attributes (5.0.x) in my big project just now. So I will be able to temporarily switch to the branch **4.7.x-dev** in my project (if 4.x is no longer supported). Thank you very much.

**Comment by alcaeus** [comment]
> Could you please copy changes from this my PR to branch 4.7.x? I can't migrate away from annotations (4.7.x) to attributes (5.0.x) in my big project just now. So I will be able to temporarily switch to the branch **4.7.x-dev** in my project (if 4.x is no longer supported). Thank you very much.

You can maintain a separate version of 4.7.x in your own fork and use that by adding a [VCS repository](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) in composer.json. 4.x is no longer supported by us, and the deprecation notices are emitted by PHP itself based on tentative return types added to the extension. They'll let you know that the return type will change in the future, but if you're not planning to upgrade (and as a matter of fact, won't be able to with 4.x) then you can safely ignore them and send them to the digital waste bin.

**Comment by andrey-tech** [comment]
> You can maintain a separate version of 4.7.x in your own fork...

Ok, there is nothing else to do.  Done — [4.7.1](https://github.com/andrey-tech/mongodb-odm-bundle/releases/tag/4.7.1).
