### PR TITLE
fix compatibility with Symfony 5.1

### LINKED ISSUE #635: Compatibility with Symfony 5.1
There seems to be some problems which I believe are connected with Symfony 5.1

https://travis-ci.org/github/doctrine/DoctrineMongoDBBundle/jobs/693203505

### PR DESCRIPTION
**Pull request by smoench**
resolves #635

### CODE REVIEW

File: Tests/FixtureIntegrationTest.php [hunk 1]
```diff
@@ -364,7 +364,12 @@ protected function configureRoutes(RouteCollectionBuilder $routes) : void
 
     protected function configureContainer(ContainerBuilder $c, LoaderInterface $loader) : void
     {
-        $c->setParameter('kernel.secret', 'foo');
+        $c->loadFromExtension('framework', [
+            'secret' => 'foo',
```
Comment (smoench) [inline Tests/FixtureIntegrationTest.php:368]: The `FrameworkExtension` of FrameworkBundle will set the `kernel.secret` parameter.

**Comment by malarzm** [comment]
Thanks a lot @smoench! :rocket:
